
import { createContext, useContext } from 'react';

export type Language = 'ar' | 'en';

export const translations = {
  ar: {
    appTitle: "نظام تقييم النظافة",
    adminTitle: "لوحة تحكم المسؤول",
    nav: {
      inspectors: "المراقبين",
      zones: "المناطق",
      checklists: "بنود التقييم",
      settings: "الإعدادات",
      backToApp: "العودة للتطبيق",
      logout: "تسجيل خروج"
    },
    inspection: {
      startNew: "بدء تقييم جديد",
      selectDetails: "قم باختيار البيانات التالية للبدء",
      startBtn: "بدء التقييم",
      myStats: "إحصائياتي",
      adminDash: "لوحة الإدارة",
      cancel: "إلغاء",
      submit: "إرسال التقييم",
      remaining: "متبقي",
      completed: "تم إنجاز",
      of: "من",
      currentScore: "النتيجة الحالية",
      successTitle: "تم الإرسال بنجاح",
      successSubtitle: "ملخص التقييم",
      finalScore: "النسبة النهائية",
      inspector: "المراقب",
      zone: "المنطقة",
      date: "التاريخ",
      time: "الوقت",
      reference: "المرجع",
      backHome: "عودة للصفحة الرئيسية",
      viewStats: "عرض إحصائياتي",
      reportDetails: "تفاصيل التقييم",
      viewSavedRecord: "عرض السجل المحفوظ",
      downloadPdf: "تحميل PDF",
      back: "عودة",
      reportHeader: "تقرير تقييم النظافة",
      electronicSignature: "هذا التقرير إلكتروني ولا يحتاج إلى توقيع",
      systemSignature: "تم الإنشاء بواسطة نظام تقييم النظافة EVS",
      additionalNotes: "ملاحظات إضافية",
      observations: "الملاحظات المرصودة",
      maxScore: "الحد الأقصى",
      score: "الدرجة",
      items: "عنصر",
      welcome: "أهلاً،",
      personalDash: "لوحة البيانات الشخصية ومتابعة الأداء",
      period: "الفترة",
      lastWeek: "آخر أسبوع",
      lastMonth: "آخر شهر",
      quarterly: "ربع سنوي",
      yearly: "سنوي",
      totalReports: "إجمالي التقارير",
      visitedZones: "المواقع التي تم تقييمها",
      avgScore: "متوسط الأداء",
      perfTrend: "تطور الأداء",
      reportHistory: "سجل التقارير",
      noReports: "لا توجد تقارير خلال هذه الفترة",
      view: "عرض",
      generalDash: "لوحة الإدارة العامة",
      generalSummary: "ملخص الأداء لجميع المراقبين",
      moreDetailsAdmin: "المزيد من التفاصيل في وضع المسؤول",
      alertComplete: "عفواً، لا يمكن إرسال التقييم.\n\nيجب تقييم جميع العناصر.",
      alertError: "حدث خطأ أثناء الإرسال",
      selectInspectorFirst: "الرجاء اختيار اسم المراقب أولاً"
    },
    actions: {
      add: "إضافة جديد",
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ",
      cancel: "إلغاء",
      export: "تصدير البيانات (JSON)",
      import: "استيراد البيانات (JSON)",
      print: "طباعة",
    },
    labels: {
      nameAr: "الاسم (عربي)",
      nameEn: "الاسم (إنجليزي)",
      username: "اسم المستخدم",
      password: "كلمة المرور",
      zoneType: "نوع المنطقة",
      maxScore: "الدرجة القصوى",
      search: "بحث...",
      obsPlaceholder: "أضف ملاحظة...",
      possibleObs: "الملاحظات الممكنة"
    },
    values: {
      HIGH_RISK: "المناطق الحرجة",
      MED_RISK: "المناطق المتوسطة الخطورة",
      GENERAL: "المناطق العادية"
    },
    messages: {
      confirmDelete: "هل أنت متأكد من الحذف؟",
      importSuccess: "تم تحديث البيانات بنجاح",
      importError: "حدث خطأ في قراءة الملف"
    }
  },
  en: {
    appTitle: "EVS Inspection System",
    adminTitle: "Admin Dashboard",
    nav: {
      inspectors: "Inspectors",
      zones: "Zones",
      checklists: "Checklist Items",
      settings: "Settings",
      backToApp: "Back to App",
      logout: "Logout"
    },
    inspection: {
      startNew: "Start New Inspection",
      selectDetails: "Select the following details to start",
      startBtn: "Start Inspection",
      myStats: "My Stats",
      adminDash: "Admin Dashboard",
      cancel: "Cancel",
      submit: "Submit Inspection",
      remaining: "Remaining",
      completed: "Completed",
      of: "of",
      currentScore: "Current Score",
      successTitle: "Submitted Successfully",
      successSubtitle: "Inspection Summary",
      finalScore: "Final Score",
      inspector: "Inspector",
      zone: "Zone",
      date: "Date",
      time: "Time",
      reference: "Reference",
      backHome: "Back to Home",
      viewStats: "View My Stats",
      reportDetails: "Inspection Details",
      viewSavedRecord: "View Saved Record",
      downloadPdf: "Download PDF",
      back: "Back",
      reportHeader: "EVS Inspection Report",
      electronicSignature: "This report is electronic and does not require a signature",
      systemSignature: "Generated by EVS Inspection System",
      additionalNotes: "Additional Notes",
      observations: "Observations",
      maxScore: "Max Score",
      score: "Score",
      items: "items",
      welcome: "Welcome,",
      personalDash: "Personal Dashboard & Performance Tracking",
      period: "Period",
      lastWeek: "Last Week",
      lastMonth: "Last Month",
      quarterly: "Quarterly",
      yearly: "Yearly",
      totalReports: "Total Reports",
      visitedZones: "Visited Zones",
      avgScore: "Average Score",
      perfTrend: "Performance Trend",
      reportHistory: "Report History",
      noReports: "No reports found for this period",
      view: "View",
      generalDash: "General Dashboard",
      generalSummary: "Performance summary for all inspectors",
      moreDetailsAdmin: "More details available in Admin Mode",
      alertComplete: "Cannot submit.\n\nPlease evaluate all items.",
      alertError: "Error during submission",
      selectInspectorFirst: "Please select an inspector first"
    },
    actions: {
      add: "Add New",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      export: "Export Data (JSON)",
      import: "Import Data (JSON)",
      print: "Print",
    },
    labels: {
      nameAr: "Name (Arabic)",
      nameEn: "Name (English)",
      username: "Username",
      password: "Password",
      zoneType: "Zone Type",
      maxScore: "Max Score",
      search: "Search...",
      obsPlaceholder: "Add a note...",
      possibleObs: "Possible Observations"
    },
    values: {
      HIGH_RISK: "High Risk Area",
      MED_RISK: "Medium Risk Area",
      GENERAL: "General Area"
    },
    messages: {
      confirmDelete: "Are you sure you want to delete?",
      importSuccess: "Data updated successfully",
      importError: "Error reading file"
    }
  }
};

export const LanguageContext = createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: any) => any;
  dir: 'rtl' | 'ltr';
}>({
  lang: 'ar',
  setLang: () => {},
  t: (k) => k,
  dir: 'rtl'
});

export const useTranslation = () => useContext(LanguageContext);
